spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: codingsendemail200@gmail.com
    password: jihe fxeu uwuv xzpc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
payment:
  vnPay:
    url: 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html'
    tmnCode: 'O9OA1R5A'
    secretKey: 'O0HK5DZHG6RSFDTTW2P9EQCKVRA9XPBP'
    returnUrl: 'http://localhost:3000/payment-success'
    version: '2.1.0'
    command: 'pay'
    orderType: 'other'

server:
  port: 8088

